### ISSUE TITLE
Java API failed to load TBB in oneAPI due to incorrect TBB version 

### ISSUE THREAD

**Issue by xwu99** [oneapi-src/oneDAL#1254]
Update: this issue is still effective for production version oneDAL 2021.1, 2021.2, 2021.3.
----------------------------------------------------------------------------------
**Describe the bug**
https://github.com/oneapi-src/oneDAL/blob/master/java/com/intel/daal/utils/LibUtils.java#L143
This line creates fullname as __libtbb.so.2__, however, in oneAPI SDK Beta 10, TBB lib version is actually __libtbb.so.12__ (/opt/intel/oneapi/tbb/2021.1-beta10/env/../lib/intel64/gcc4.8/libtbb.so.12), leads to libJavaAPI.so failed to load. 

$ ldd libJavaAPI.so
        linux-vdso.so.1 (0x00007ffcf95d3000)
        libtbb.so.12 => not found
        libtbbmalloc.so.2 => not found
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd499f45000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd499ba7000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fd49998f000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd49959e000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fd49939a000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fd4a7f60000)

**To Reproduce**
Call any Java API in oneAPI beta 10

**Environment:**
 - OS: [e.g. Ubuntu 18.04]
 - Version: [oneAPI beta 10]

**Comment by xwu99** [comment]
@napetrov @PIVOVAR3AL

**Comment by napetrov** [comment]
@SmirnovEgorRu @owerbat

**Comment by xwu99** [comment]
I thought this issue is still effective for production version oneDAL 2021.1.1.
