### ISSUE TITLE
Major behavioral difference between java array-backed homogen table and native-heap backed homogen table.

### ISSUE THREAD

**Issue by cnuernber** [oneapi-src/oneDAL#1361]
**Describe the bug**

The bytebuffer homogen table does not write to the `buf` argument to getBlockOfRows while the array buffer implementation does.  Furthermore the bytebuffer homogen table forces the row-block to be allocated again meaning there needs to be another 2x dataset size memory available.

- [bytebuffer homogen table getBlockOfRows](https://github.com/oneapi-src/oneDAL/blob/master/java/com/intel/daal/data_management/data/HomogenNumericTableByteBufferImpl.java#L159)
- [array homogen table getBlockOfRows](https://github.com/oneapi-src/oneDAL/blob/master/java/com/intel/daal/data_management/data/HomogenNumericTableArrayImpl.java#L170)

**Comment by PivovarA** [comment]
Hi @cnuernber 
Thanks for pointing out this issue. We'll check it and come back with an answer as soon as possible

**Comment by napetrov** [comment]
Java support is deprecated in oneDAL and will be moved to https://github.com/oap-project/oap-mllib/pull/336
