### ISSUE TITLE
ALS algorithm failed to solve a system of normal equations

### ISSUE THREAD

**Issue by xwu99** [oneapi-src/oneDAL#1513]
**Describe the bug**
oneDAL distributed ALS output: 

terminate called after throwing an instance of 'daal::services::interface1::Exception'
  what():  ALS algorithm failed to solve a system of normal equations

**To Reproduce**

Ratings DataSet:

8,9,1.4411745
9,1,1.092935
9,2,-0.91744214
9,3,2.2006998
9,9,0.21981817
10,1,1.0850104
11,5,1.3231134
11,6,1.7639855
11,7,0.11663926
12,3,2.00351
12,4,0.6138814
13,3,-1.2167481
13,6,0.18907101
13,8,1.4609658
14,2,0.14865299
14,5,0.40862167
14,6,0.6963652
14,7,-0.23756275
15,6,1.5642234
15,7,0.66677445
15,9,1.000214
16,0,1.6124529
16,2,-1.6973028
16,8,2.1447284
16,9,0.05045301
18,4,0.33858204
18,5,0.18965948
18,8,0.33005014
19,6,0.9575896
0,2,0.26225922
0,6,0.79922354
0,7,0.49164158
1,0,0.5854655
1,6,-0.035676636
1,8,0.5337034
2,7,0.42522684
3,2,0.13153574
3,4,0.2896202
3,5,1.5807452
3,9,1.4361646
4,0,0.26508853
4,6,0.01327089
4,7,0.9329253
4,9,1.8566762
5,0,0.7780668
5,5,0.08633061
5,6,0.08109148
6,1,2.1982207
6,3,2.8123326
6,5,0.8729558
6,6,1.1040335
6,7,0.413112
6,8,0.6773266
7,0,0.7310588
7,1,-2.8301759
7,3,1.1037079
8,5,-0.7674738
8,7,0.4774422

numUsers = 20, numItems = 10
maxIter = 10, rank = 5, regParam = 0.01, implicitPrefs = true

**Expected behavior**
Return result matrices successfully

**Comment by Alexsandruss** [comment]
Fixed by https://github.com/oneapi-src/oneDAL/commit/c6c5219c85e5bceb0392e54e653e00e8cc45e21f commit / https://github.com/oneapi-src/oneDAL/pull/1533 PR.

**Comment by Alexsandruss** [comment]
@xwu99, did https://github.com/oneapi-src/oneDAL/commit/c6c5219c85e5bceb0392e54e653e00e8cc45e21f fix your case?

**Comment by xwu99** [comment]
> @xwu99, did [c6c5219](https://github.com/oneapi-src/oneDAL/commit/c6c5219c85e5bceb0392e54e653e00e8cc45e21f) fix your case?

Thanks for the fix. I am working on another algorithm. I will validate ALS and let you know.

**Comment by xwu99** [comment]
closed the issue.
