### ISSUE TITLE
[CentOS 7]YUM installation of intel-oneapi-dal-devel-2021.1.1 met conflicts 

### ISSUE THREAD

**Issue by HongW2019** [oneapi-src/oneDAL#1552]
**Describe the bug**
```
yum install  intel-oneapi-dal-devel-2021.1.1

Error: intel-oneapi-compiler-shared-common-runtime-2021.2.0 conflicts with intel-oneapi-common-licensing-2021.1.1-2021.1.1-60.noarch
Error: intel-oneapi-openmp-common-2021.2.0 conflicts with intel-oneapi-common-licensing-2021.1.1-2021.1.1-60.noarch
Error: intel-oneapi-tbb-devel-2021.2.0 conflicts with intel-oneapi-common-licensing-2021.1.1-2021.1.1-60.noarch
Error: intel-oneapi-tbb-common-devel-2021.2.0 conflicts with intel-oneapi-common-licensing-2021.1.1-2021.1.1-60.noarch
Error: intel-oneapi-common-vars conflicts with intel-oneapi-common-licensing-2021.1.1-2021.1.1-60.noarch
Error: intel-oneapi-openmp-2021.2.0 conflicts with intel-oneapi-common-licensing-2021.1.1-2021.1.1-60.noarch
Error: intel-oneapi-compiler-dpcpp-cpp-runtime-2021.2.0 conflicts with intel-oneapi-common-licensing-2021.1.1-2021.1.1-60.noarch
Error: intel-oneapi-compiler-shared-runtime-2021.2.0 conflicts with intel-oneapi-common-licensing-2021.1.1-2021.1.1-60.noarch
Error: intel-oneapi-tbb-2021.2.0 conflicts with intel-oneapi-common-licensing-2021.1.1-2021.1.1-60.noarch
Error: intel-oneapi-tbb-common-2021.2.0 conflicts with intel-oneapi-common-licensing-2021.1.1-2021.1.1-60.noarch

```

**Environment:**
 - OS: [ CentOS 7 , eg. 7.6.1810,  7.9.2009 ) ]
 - Compiler: [e.g. 4.8.5 , 7.3.0]

**Comment by HongW2019** [comment]
This is very similar to my case in CentOS 7. https://community.intel.com/t5/Registration-Download-Licensing/Yum-installation-of-OneMKL-results-in-conflict-error/m-p/1267827#M562.

**Comment by SmirnovEgorRu** [comment]
Hi @HongW2019,
did you try to download the latest version - 2021.2? Is there the same issue?

**Comment by HongW2019** [comment]
> Hi @HongW2019,
> did you try to download the latest version - 2021.2? Is there the same issue?
There is a issue in RPMs in the Gold release (2021.1.*), so we tried the 2021.2 and it works now.

**Comment by PivovarA** [comment]
Hi @HongW2019 
Thanks a lot for pointing this out. The issue you have described is a known issue with the oneAPI 2021.1 gold release.
The initial release, 2021.1, of the oneAPI Toolkits, component packages, and runtime libraries provided or distributed by the Intel repositories for Linux package managers, YUM/DNF or ZYPPER, have a flaw that will prevent upgrades to future oneAPI releases.
You can read more about the problem itself and how to solve it [here](https://software.intel.com/content/www/us/en/develop/articles/yum-dnf-apt-zypper-packages-oneapi-2021-1-gold.html)
Also I would like to say that I tried to install oneDAL 2021.2 on CentOS 7 and it was installed without problems.

**Comment by HongW2019** [comment]
> Hi @HongW2019
> Thanks a lot for pointing this out. The issue you have described is a known issue with the oneAPI 2021.1 gold release.
> The initial release, 2021.1, of the oneAPI Toolkits, component packages, and runtime libraries provided or distributed by the Intel repositories for Linux package managers, YUM/DNF or ZYPPER, have a flaw that will prevent upgrades to future oneAPI releases.
> You can read more about the problem itself and how to solve it [here](https://software.intel.com/content/www/us/en/develop/articles/yum-dnf-apt-zypper-packages-oneapi-2021-1-gold.html)
> Also I would like to say that I tried to install oneDAL 2021.2 on CentOS 7 and it was installed without problems.

@PivovarA Thanks for this detailed information. We decided to choose the 2021.2 to avoid these conflicts.

**Comment by PivovarA** [comment]
Great! 
@HongW2019 can we close this issue ?
