### ISSUE TITLE
GBT Model failed to serialize with compressor.

### ISSUE THREAD

**Issue by cmsxbc** [oneapi-src/oneDAL#1707]
**Describe the bug**
I'm working on convert lightGBM model to daal Model,  a model which contains 28 feature and 208 trees, can't be serialized with compressor. The size of archive is 0, and there is no any error.

**To Reproduce**

A reproducible model can be found here: https://github.com/cmsxbc/poc4issue/tree/main/oneapi-src/oneDAL/1707

```C++
void dumpModel(daal::algorithms::gbt::regression::ModelPtr model) {
    daal::data_management::InputDataArchive dataArch;
    model->serialize(dataArch);
    size_t size = dataArch.getSizeOfArchive();
    std::cout << "without compressor size: " << size << std::endl;
    if (size == 0) { // false
        std::cout << "errors: " << dataArch.getErrors()->getDescription() << std::endl;
        return;
    }

    daal::data_management::Compressor<daal::data_management::lzo> compressor;
    daal::data_management::InputDataArchive cDataArch(&compressor);
    model->serialize(cDataArch);
    size = cDataArch.getSizeOfArchive();
    std::cout << "with compressor size: " << size << std::endl;
    if (size == 0) { // true
        std::cout << "errors: " << cDataArch.getErrors()->getDescription() << std::endl;
        return;
    }
}
```

**Expected behavior**
Serialize correctly.

**Output/Screenshots**
![2021-06-09-210954_634x147_scrot](https://user-images.githubusercontent.com/3500109/121360658-31d83700-c967-11eb-8aa2-6e4d13cd773a.png)

**Environment:**
 - OS: ArchLinux
 - Compiler: Intel(R) oneAPI DPC++ Compiler 2021.2.0 (2021.2.0.20210317)
 - Version: 2021.2.0

**Comment by ShvetsKS** [comment]
@cmsxbc Thanks a lot for reporting it!
trying to fix it

**Comment by ShvetsKS** [comment]
Some observation:
I checked serialization of the model with/without compression on model builder example: https://github.com/oneapi-src/oneDAL/blob/master/examples/daal/cpp/source/gradient_boosted_trees/gbt_cls_traversed_model_builder.cpp

just added serialization into `testModel` function:

```cpp
size_t testModel(daal::algorithms::gbt::classification::ModelPtr modelPtr)
{

    daal::data_management::InputDataArchive dataArch;
    modelPtr->serialize(dataArch);
    size_t size = dataArch.getSizeOfArchive();
    std::cout << "without compressor size: " << size << std::endl;

    daal::data_management::Compressor<daal::data_management::lzo> compressor;
    daal::data_management::InputDataArchive cDataArch(&compressor);
    modelPtr->serialize(cDataArch);
    size = cDataArch.getSizeOfArchive();
    std::cout << "with compressor size: " << size << std::endl;
...
```

and the size is different from `0` in both cases.

**Comment by cmsxbc** [comment]
@ShvetsKS yep, i had same observation. Not all of my models will get 0 size with compressor. But i cannot find the pattern of the models.
It seems that it works fine with small model; Only big models with thousands of nodes in total will get wrong result.

**Comment by cmsxbc** [comment]
I updated my issues model: https://github.com/cmsxbc/poc4issue/tree/main/oneapi-src/oneDAL/1707
It shows that it begin to failed when there is 34 trees.

**Comment by ShvetsKS** [comment]
@cmsxbc to be exactly 34'th tree is reason of fail.
If we use just one `buildTree34` tree  it's also fail.

**Comment by cmsxbc** [comment]
@ShvetsKS I found that the `getErrors` of `InputDataArchive` does not contain the errors raised from `_arch` and `CompressionStream`, which used by `InputDataArch` with compressor.
I just modified the header and add the certain methods, the reason of fail is showed that it failed in `CompressionStream` with
`Size of output stream is not enough to start compression`

![2021-06-12-220853_1186x123_scrot](https://user-images.githubusercontent.com/3500109/121778741-e02fe680-cbca-11eb-8ad9-c72f6f7346aa.png)

**Comment by ShvetsKS** [comment]
@cmsxbc please check the fixed error handling: https://github.com/oneapi-src/oneDAL/pull/1723
now we can see errors description:
```
with compressor size: 0
errors: Size of output stream is not enough to start compression
```

**Comment by ShvetsKS** [comment]
PR #1723 was reworked with throwing an exception
