### ISSUE TITLE
ridgeParameters has not effect in distributed Ridge Regression

### ISSUE THREAD

**Issue by xwu99** [oneapi-src/oneDAL#1726]
**Describe the bug**
ridgeParameters has no effect in distributed Ridge Regression

See also: https://github.com/intel/scikit-learn-intelex/discussions/620

I also reproduced this with C++ interfaces.  No matter what ridgeParameters I set, the results are always the same.

```
NumericTablePtr ridgeParams(new HomogenNumericTable<double>(
        1, 1, NumericTable::doAllocate, regParam));
ridge_regression::training::Distributed<step1Local> localAlgorithm;
localAlgorithm.parameter.ridgeParameters = ridgeParams;

/* Pass a training data set and dependent values to the algorithm */
localAlgorithm.input.set(ridge_regression::training::data, pData);
localAlgorithm.input.set(ridge_regression::training::dependentVariables, pLabel);

/* Train the multiple ridge regression model on local nodes */
localAlgorithm.compute();
```

**Comment by OnlyDeniko** [comment]
Please, try to set parameter on ```step2Master```

For example:
```c++
training::Distributed<step2Master> masterAlgorithm;
masterAlgorithm.parameter.ridgeParameters = ridgeParams;
```

**Comment by xwu99** [comment]
@OnlyDeniko Thanks for your suggestion! I used your method, but the result is still the same. It seems the ridge parameter is not applied. Pls check https://github.com/intel/scikit-learn-intelex/discussions/620 as well.

**Comment by OnlyDeniko** [comment]
@xwu99 I've checked out and can not reproduce the problem. Can you share your reproduce code?

**Comment by xwu99** [comment]
Did you see different result with/without ridgeParameter? I see the results are all the same whatever you set it.
________________________________
发件人: Kulandin Denis ***@***.***>
发送时间: Monday, July 5, 2021 8:36:50 PM
收件人: oneapi-src/oneDAL ***@***.***>
抄送: Wu, Xiaochang ***@***.***>; Mention ***@***.***>
主题: Re: [oneapi-src/oneDAL] ridgeParameters has not effect in distributed Ridge Regression (#1726)


@xwu99<https://github.com/xwu99> I've checked out and can not reproduce the problem. Can you share your reproduce code?

―

**Comment by OnlyDeniko** [comment]
`alpha=0.5`
Ridge Regression prediction results: (first 10 rows):
```
-1653.421 1107.380
-1795.871 -46.809
-1198.459 -2120.880
701.356   -1031.682
-516.961  901.440
-1989.919 -102.352
1039.367  -937.589
1922.106  -41.790
-428.547  372.803
1796.245  210.501
```
`alpha=100`
Ridge Regression prediction results: (first 10 rows):
```
-1653.368 1107.343
-1795.821 -46.807
-1198.423 -2120.816
701.332   -1031.641
-516.944  901.416
-1989.863 -102.349
1039.335  -937.561
1922.051  -41.782
-428.540  372.793
1796.200  210.493
```

**Comment by xwu99** [comment]
The issue is caused by incorrect setting of interceptFlag. If not explictly set interceptFlag, for daal4py, the default value is False, however for C++, its default value is True. This default value inconsistency should be addressed seperatly.
