### ISSUE TITLE
How to make a debug build (missing daal_vmlipp_cored.lib)?

### ISSUE THREAD

**Issue by emmenlau** [oneapi-src/oneDAL#2114]
**Describe the bug**
I would like to make a debug build of DAAL using the supplied `makefile` on Windows. I found that there is option `REQDBG` but that does not seem to set the debug runtime. Then I found the option `MSVC_RUNTIME_VERSION=debug` that seems to do what I want. However the build fails very early on with error:
```
make: *** No rule to make target '__deps/mklfpk/win/lib/intel64/daal_vmlipp_cored.lib', needed by 'tmp_build_files/work/daal/lib/onedal_cored.lib'.  Stop.
```

**To Reproduce**
1. Checkout latest oneDAL release
2. Open a Cygwin prompt with Visual Studio 2022 settings
3. Call `make -f makefile  REQDBG=true MSVC_RUNTIME_VERSION=debug WORKDIR=tmp_build_files/work RELEASEDIR=tmp_build_files/release REQCPU="sse42 avx avx2" _daal_core _daal_thr_tbb _daal_thr_seq _release_c PLAT=win32e COMPILER=vc` 

**Expected behavior**
The build should work.

**Environment:**
 - OS: Windows 11 with Cygwin for bash and make
 - Compiler: Visual Studio 2022 x64 current latest

**Comment by PivovarA** [comment]
Hi @emmenlau 
Thanks for pointing out the issue
It looks like you don't have mklfpk installed. 
You can find it [here](https://github.com/oneapi-src/oneDAL/releases/tag/Dependencies)
As an option, you can use this script to download [mklfpk lib for windows](https://github.com/oneapi-src/oneDAL/blob/master/dev/download_micromkl.bat) or for [macos or linux](https://github.com/oneapi-src/oneDAL/blob/master/dev/download_micromkl.sh). 
You can find it in dev directory (check  fifth paragraph of [installation guide](https://github.com/oneapi-src/oneDAL/blob/master/INSTALL.md#installation-steps))

**Comment by emmenlau** [comment]
Hi @PivovarA , I think I have been running the script that downloads the mklfpk, at least the release build works without problems. Only debug builds fails with above error. Also, I can see that the mklfpk libs *without* the debug suffix `d` are present, while the ones with the debug suffix are not. Could you check that the mklfpk archive contains actually debug libs?

Here is what I see:
```
#> ls -la '__deps/mklfpk/win/lib/intel64/'
total 300380
drwxrwx--- 2 user user      4096 Apr 12 17:30 .
drwxrwx--- 3 user user      4096 Apr 12 17:28 ..
-rw-rw---- 1 user user 127403642 Apr 12 17:29 daal_mkl_sequential.lib
-rw-rw---- 1 user user 145704614 Apr 12 17:30 daal_mkl_thread.lib
-rw-rw---- 1 user user  34465608 Apr 12 17:30 daal_vmlipp_core.lib
```

So there are no debug libs, or am I on the wrong track?

**Comment by emmenlau** [comment]
@PivovarA can you help with this?

**Comment by napetrov** [comment]
We do not provide debug fpk versions currently . Will see if this would be feasible to provide, but can't guarantee this would be soon

**Comment by emmenlau** [comment]
Thanks @napetrov for the reply! The problem without a debug fpk version is that I can not correctly build oneDAL in debug. It is difficult to support oneDAL development without a debug build...

**Comment by napetrov** [comment]
@emmenlau - please see versions updated here - https://github.com/oneapi-src/oneDAL/pull/2245
New FPK archives contains MDd versions 
<img width="116" alt="image" src="https://user-images.githubusercontent.com/18015221/213161158-d873b19b-fdfa-435d-a77d-cfe08c687a12.png">

**Comment by emmenlau** [comment]
Awesome! Thanks @napetrov and all involved!
