### ISSUE TITLE
Remote branch develop not found in upstream origin

### ISSUE THREAD

**Issue by vineel96** [oneapi-src/oneDAL#2388]
Hi,
In installation steps of building from sources, first step says to clone from "develop" branch. But there is no such branch available in the repo. Please update the steps here: https://github.com/oneapi-src/oneDAL/blob/master/INSTALL.md#installation-steps

**Comment by napetrov** [comment]
@vineel96  - thanks for catching. This can be any branch - ether stable release - 2023.1.1 is latest release or current master.

**Comment by vineel96** [comment]
Hi,
Thanks for the information.
