### ISSUE TITLE
How to validate results when adding a new backend (i.e., OpenBLAS, Lapack, etc)

### ISSUE THREAD

**Issue by ajay-fuji** [oneapi-src/oneDAL#2549]
Hi, 

As we can see that oneDAL has integrated support for OpenBLAS as replacement to MKL for backend. 
I am wondering, when we change backend, how validation of algorithms accuracy or validation of output result of any algorithm is done?

Since MKL and OpenBLAS has different ways of performing computation, how do we make sure that we are getting correct results (algorithm) with any of the backend?

Thanks!

**Comment by napetrov** [comment]
The current validation of MKL backend consists of:
1. examples
2. test systems - there is public bazel integrated test system for oneDAL interfaces and closed internal test system for DAAL interface.
3. Integration testing with scikit-learn-intelex - so scikit-learn test suite executed against enabled algorithm and ensure validation of conformance to scikit-learn. 

As for OpenBLAS backend - currently it consist only of examples validation: 
https://github.com/oneapi-src/oneDAL/blob/master/.ci/pipeline/ci.yml#L112

I wouldn't say openBLAS is replacement  but rather is alternative. Also this is first step towards ports to ARM/RISC-V and the  assumption there is that there would be corresponding extension of validation for those configurations. 

It have to be driven by corresponding team/individuals interested in that support.
