### ISSUE TITLE
How to perform LightGBM inference in online mode using c++?

### ISSUE THREAD

**Issue by GIRVANAL** [oneapi-src/oneDAL#2634]
Hello everyone.
I found an similar issue #1530 , which provides an example of training a LightGBM model in python and performing predictions in c++ 
However, it seems that the inference stage of this example utilizes batch mode.
```
    /* Create an algorithm object to predict values of gradient boosted trees classification */
    daal::algorithms::gbt::classification::prediction::Batch<> algorithm(nClasses);
    
    /* Pass a testing data set and the deserialized/trained model to the algorithm */
    algorithm.input.set(classifier::prediction::data, testData);
    algorithm.input.set(classifier::prediction::model, deserialized_model);
    
    /* Predict values of gradient boosted trees classification */
    algorithm.compute();
```

While exploring the oneDAL source code [gbt_classification_predict.h](https://github.com/oneapi-src/oneDAL/blob/main/cpp/daal/include/algorithms/classifier/classifier_predict.h), I couldn't find the `Online<>` interface in the predict satge.
So, is it possible to preform inference in online mode for c++?

Thank you for your assistance!

**Comment by napetrov** [comment]
Can you please elaborate more on usecase?
Usually Online interfaces are used for training - basically this would allow you to continue training on new data and don't stop it with batch end.   For prediction i'm not sure what the intended use here?  You can run predictions for as many runs as you want

**Comment by GIRVANAL** [comment]
> Can you please elaborate more on usecase? Usually Online interfaces are used for training - basically this would allow you to continue training on new data and don't stop it with batch end. For prediction i'm not sure what the intended use here? You can run predictions for as many runs as you want

Thanks. I think that I may have misunderstood this concept.

Here is my usecase: I've trained a LightGBM model in python, and my goal is to provide an online prediction service, seepding up the prediction process using c++.
So, does it mean that everytime i get new data, i can reset the `algorithm.input`, and rerun the prediction `algorithm.compute()`?

By the way, are there any ways to perform predictions using a single core?

**Comment by napetrov** [comment]
Yes, you can just run new compute instances.   But i would argue that you would be getting lot of benefits from C++ level predictions.  

If you don't have C++ code around that you extending to support predictions - i would just try using python level predictions with ModelBuilders - https://intelpython.github.io/daal4py/model-builders.html

@Alexandr-Solovev @Alexsandruss  - can you comment on proper way for forcing C++ code to use 1 core only?

**Comment by Alexandr-Solovev** [comment]
Hi @GIRVANAL ! Do you mean a single thread usage or a single core usage?

**Comment by GIRVANAL** [comment]
> Hi @GIRVANAL ! Do you mean a single thread usage or a single core usage?

Hi. My original intention was to perform predictions on a single core only, and i believe that there is no necessity for utilizing multiple threads on a single core. Therefore, a single thread may be sufficient. Is there any difference between these two usages?

**Comment by Alexandr-Solovev** [comment]
@GIRVANAL you can use a replacing default number of threads as in this example:
https://github.com/oneapi-src/oneDAL/blob/main/examples/daal/cpp/source/set_number_of_threads/set_number_of_threads.cpp

**Comment by GIRVANAL** [comment]
Thanks a lot! I will give it a try.
