### ISSUE TITLE
LinuxMakeGNU_OpenBLAS_x86 and LinuxMakeLLVM_OpenBLAS_rv64 Public CI failing

### ISSUE THREAD

**Issue by ethanglaser** [oneapi-src/oneDAL#2758]
**Describe the bug**
Failures are occurring during Azure Pipelines runs on these steps of public CI as of recent - check any open PR for example of failures:
![image](https://github.com/oneapi-src/oneDAL/assets/42726565/cf00bf0b-b3e9-429e-aa5f-fadf09728dbe)
![image](https://github.com/oneapi-src/oneDAL/assets/42726565/2b48a19a-887b-4fa6-8510-0c371a1cbc3b)

@keeranroth any idea where these might be coming from?

**Comment by keeranroth** [comment]
The exec format error is a problem with QEMU and binfmt. I'll have a look
tomorrow. It's a public holiday today. I'm not sure about the illegal
instructions, but if that is on the riscv build,  it's likely to do with
the qemu setup as well

**Comment by keeranroth** [comment]
https://github.com/oneapi-src/oneDAL/pull/2762 should fix this. The riscv64 issue was easy enough, as the location of the downloaded QEMU had changed. I suspect that the error on x86_64 is a corrupted OpenBLAS build, as I can't reproduce it locally. Giving a key that hasn't been cached yet should fix things 🤞

**Comment by ethanglaser** [comment]
Should indeed be fixed by https://github.com/oneapi-src/oneDAL/pull/2762. Closing.
