### ISSUE TITLE
Inconsistent Interface for constructing different classifier.

### ISSUE THREAD

**Issue by Mightrider** [oneapi-src/oneDAL#299]
**Describe the bug**
I tried to create some training classifier using template functions. Unfortunately some of them **need** the number of classes(Decision Forest) , some of them **can't** take the number of classes (KNN), and some don't care. For consistency It would be nice to be able to construct all classifier either with or without the number of classes.

For DecisionTree it is even less consistent with a training constructor only working with nClasses and a prediction one working only without nClasses. This also raises the question why is the number of classes not part of the model anyway?

**To Reproduce**
```c++
#include <daal.h>

int main() {
    size_t nClasses = 4;
    daal::algorithms::decision_forest::classification::training::Batch<> decisionForest(nClasses);
    daal::algorithms::multi_class_classifier::training::Batch<> multiClass(nClasses);
    // This one does not compile
    daal::algorithms::kdtree_knn_classification::training::Batch<> knn(nClasses);

    // This one does not compile
    daal::algorithms::decision_forest::classification::training::Batch<> decisionForest2;
    daal::algorithms::multi_class_classifier::training::Batch<> multiClass2;
    daal::algorithms::kdtree_knn_classification::training::Batch<> knn2;
}
```

**Environment:**
 - OS: [Ubuntu 18.04]
 - Compiler: [GCC7.4]
 - Version: [2019 Update 5]

**Comment by PivovarA** [comment]
Hi, @Mightrider . Thank you very much for covering this moment. Indeed, we have some inconsistency. In general the idea is that the constructor receives parameters, some of these parameters have default values, and some haven't. Obviously, nClasses is one of those parameters that haven't default value. So parameters of the constructor of those classes will be different anyway.
However, this problem can be solved on the application level and a solution may be offered depending on the version of c ++ that you are using. 
It would be great if you could describe your use case in more details to help us to choose the right strategy for solving this problem. Please note that after you construct required class you will need to specify algorithm parameters that are different for different algorithms. For example it can be some factory or something else.

**Comment by Mightrider** [comment]
Hi, @PivovarA. Thank you for your quick reply. I try to motivate my problem as simple as possible and I attached some code which will hopefully help a bit.

Basically I want a generic class which is able to construct and hold any of the daal classifier. My `TemplatedClassifier` should be able to create the training and prediction object but due to the fact that some of the classifier have a default for nClasses and some need it as a parameter, I need to treat them accordingly and write the explicit constructor.

The problem could be solved if all classifier would offer a constructor with or without nClasses as parameter.

Another inconsistency I stumbled over is that some classifier use a method to access the parameter instead of accessing the object directly. But I guess this is based on a more complex design decision.

```c++
#include <daal.h>
#include <memory>

/**
 * @brief Abstract Classifier class for generic handling.
 */
class Classifier {
public:
    // provide some virtual methods here like:

    //virtual void train(...);
    //virtual void classify(...);

};

/**
  * @brief Templated Classifier. Takes care things based on classifier type.
  */
template<typename T, typename U>
class TemplatedClassifier : public Classifier {
public:
    using TrainerType = T;
    using PredictorType = U;

    TemplatedClassifier(size_t nClasses);
    virtual ~TemplatedClassifier() = default;

protected:
    /* We need pointer here because not all classifier have an default constructor. */
    std::unique_ptr<T> mTrainingClassifier;
    std::unique_ptr<U> mPredictionClassifier;
};

/* In general I can create my unique_ptr and pass the number of classes directly. */
template<typename T, typename U>
TemplatedClassifier<T, U>::TemplatedClassifier(size_t nClasses) {
    mTrainingClassifier = std::make_unique<TemplatedClassifier::TrainerType>(nClasses);
    mPredictionClassifier = std::make_unique<TemplatedClassifier::PredictorType>(nClasses);
};

/* For the special case I can write this constructor to make it work. */
template<>
TemplatedClassifier<daal::algorithms::kdtree_knn_classification::training::Batch<>,
                    daal::algorithms::kdtree_knn_classification::prediction::Batch<>>::TemplatedClassifier(size_t nClasses) {
    mTrainingClassifier = std::make_unique<TemplatedClassifier::TrainerType>();
    mTrainingClassifier->parameter.nClasses = nClasses;
    mPredictionClassifier = std::make_unique<TemplatedClassifier::PredictorType>();
    mPredictionClassifier->parameter.nClasses = nClasses;
};

template<>
TemplatedClassifier<daal::algorithms::logistic_regression::training::Batch<>,
                    daal::algorithms::logistic_regression::prediction::Batch<>>::TemplatedClassifier(size_t nClasses) {
    mTrainingClassifier = std::make_unique<TemplatedClassifier::TrainerType>(nClasses);
    mPredictionClassifier = std::make_unique<TemplatedClassifier::PredictorType>(nClasses);
    // Obviously I already set nClasses but it is strange that I need to call parameter().nClasses here instead of parameter.nClasses
    mTrainingClassifier->parameter().nClasses = nClasses;
    mPredictionClassifier->parameter().nClasses = nClasses;
};

int main() {
    std::shared_ptr<Classifier> vPtr1 = std::make_shared<TemplatedClassifier<daal::algorithms::kdtree_knn_classification::training::Batch<>,
                                                                             daal::algorithms::kdtree_knn_classification::prediction::Batch<>>>(2);

    std::shared_ptr<Classifier> vPtr2 = std::make_shared<TemplatedClassifier<daal::algorithms::decision_forest::classification::training::Batch<>,
                                                                             daal::algorithms::decision_forest::classification::prediction::Batch<>>>(2);

    std::shared_ptr<Classifier> vPtr3 = std::make_shared<TemplatedClassifier<daal::algorithms::logistic_regression::training::Batch<>,
                                                                             daal::algorithms::logistic_regression::prediction::Batch<>>>(2);
}
```

**Comment by PivovarA** [comment]
Hello, @Mightrider 
I apologize for the long delay in reply. 
The situation with `nClasses` is clear and, as I said earlier, we really have an some inconsistency.
However, it is obvious that some parameters have default values ​​and some don't. `nClasses` is just an example of such a parameter that does not have a default value. The point is how to set parameter values ​​that have no default value. I will clarify that without setting values ​​for such parameters, you will get an error on `compute` step.
In the example that you provided, it is not clear, so our question is: How exactly you will set those parameters that don't have a default value ?
Depending on this answer, we will be able to provide the most optimal solution. Either offer a solution without changing the library code, or, for example, provide a constructor with empty parameter values.

**Comment by Mightrider** [comment]
Hello @PivovarA,
I know that some classifier have parameter without a default value and that I need to handle those. 
But as far as I know none of them are needed for the construction of the object. Only `nClasses` is needed in some cases. And honestly for me it is kind of arbitrary whether nClasses has a default value or not. So my focus is on a simple and generic construction of classifiers. Indeed a constructor with empty parameter values would be really helpful.

**Comment by PivovarA** [comment]
Hello @Mightrider 

I created a PR (#459) with a fix. I added new constructors to binary classifiers (SVM and brownboost), so now they will not throw errors if you put nClasses there. 
I want to focus your attention to the fact that these classifiers are binary, which means that they will return an exception if you pass nClasses> 2.
The situation with KNN is a bit more complicated, and this problem will be resolved in the near future.

**Comment by emmenlau** [comment]
Awesome, thanks!

**Comment by PivovarA** [comment]
Hello @Mightrider
New constructors for svm and brownboost were added to the master branch

**Comment by Mightrider** [comment]
Nice! I will take a look at!

**Comment by Alexsandruss** [comment]
Hello @Mightrider, new kNN constructors with nClasses were added to master in https://github.com/oneapi-src/oneDAL/pull/1392

**Comment by PivovarA** [comment]
Hi @Mightrider 
Can we close this issue ?

**Comment by emmenlau** [comment]
Thanks @PivovarA , @Alexsandruss and all!
