### ISSUE TITLE
Policy to set training cache size, and negative trade-off of larger cache?

### ISSUE THREAD

**Issue by emmenlau** [oneapi-src/oneDAL#369]
This is not a bug, but rather an implementation question.

After a longer investigation of a performance bottleneck with SVM classifier, we just discovered the training `cacheSize` and its strong impact on performance. In our tests, if the cache size is exceeded by just a few bytes, we see a sudden, huge drop in performance of 30x-100x (in words: one hundred times slower). So the cache is hugely beneficial, nice work!

Now the questions:
 1. Would it be possible that DAAL could make better use of the existing cache? It was surprising to see such a gigantic, steep difference in performance when hitting the cache size. Is there something DAAL internally could do to make this jump less drastic, like shuffling data in and out of the cache?
 2. Would it be possible that DAAL could optimize this parameter automatically? For example a value of `int::max` could indicate that DAAL should allocate as much as required but not more?
 3. We found that cache must be larger than the training data. Is there a formula for the required cache size, given the size of the feature set? We estimated a factor `10`, is that about correct?
 4. Is there any negative trade-off of setting a large cache (except that it requires more RAM)? I.e. would it be sensible to set cache sizes of 100MB, 1000MB, 10000MB, or more? Or is there an upper limit?

**Comment by SmirnovEgorRu** [comment]
@emmenlau, our current SVM implementation has 2 scenarios:
1) if ```cacheSize >= n^2*sizeof(FPtype)``` - it means the best performance for DAAL, because we store whole kernel matrix in memory and compute this only once. (n - number of observations in the data set)
2) In another case - **cache will not be used at all** and algorithm will be slower than in the first case.

Anyway, we are thinking on adding partial usage of cache to speedup the second scenario, as it's used in other places.

>> Is there any negative trade-off of setting a large cache

I didn't observe such things

**Comment by emmenlau** [comment]
Dear @SmirnovEgorRu , thanks this sounds very good! We did a few more checks on cache size and guessed already that `cacheSize >= n^2*sizeof(FPtype)` may be the magic sauce! Thanks for the confirmation. We also guessed that the cache currently is an on-off-thing: either its sufficiently large and can be used or it does not help at all.

> Anyway, we are thinking on adding partial usage of cache to speedup the second scenario, as it's used in other places.

This would be great! We can certainly afford a `cacheSize` of a few GB, but it would be sad if everything below 100% of `n^2*sizeof(FPtype)` does not add any benefit at all.

> > > Is there any negative trade-off of setting a large cache
> 
> I didn't observe such things

That is great news, then we will for now always set `n^2*sizeof(FPtype)` unless it exceeds our RAM restrictions, in which case we fall back to no cache. That is pretty good for now.

**Comment by emmenlau** [comment]
Should we leave the issue open until an improved caching policy exists, or would you like to close it? My immediate questions are now answered, thanks!

**Comment by SmirnovEgorRu** [comment]
@emmenlau, sure - keep it open. It will be additional significant reason to implement the feature :)

I'm happy that it helped you at least for short term.

**Comment by SmirnovEgorRu** [comment]
@emmenlau, we added ThunderSVM method for SVM https://github.com/oneapi-src/oneDAL/pull/615. It works significant faster than the current version and doesn't have strong dependency on cache size.

**Comment by emmenlau** [comment]
Thanks a lot @SmirnovEgorRu , this solves the problem for us. I will close the issue. Nice work!
