### ISSUE TITLE
New oneDAL interfaces are not reflected in the docs

### ISSUE THREAD

**Issue by michael-smirnov** [oneapi-src/oneDAL#649]
There is no information about new interfaces in the docs and help messages. 
I think we need to:
- shortly explain differences between content in **daal** and **oneapi/dal** folders in README.md
- add documentation (at least notes for short-term?) about new interfaces
- update makefile help messages about how to build oneDAL.
- in makefiles for oneDAL examples, cleanup old wordings e.g. "DAAL", "Intel Data Analytics Acceleration Library".

**Comment by napetrov** [comment]
@michael-smirnov  @rlnx  @outoftardis   - guess we can close this issue now?

**Comment by outoftardis** [comment]
> @michael-smirnov @rlnx @outoftardis - guess we can close this issue now?

I guess so, yes. However, I'm not sure about makefiles.
